M48
; DRILL file {KiCad (6.0.4-0)} date Wednesday, 24 August 2022 at 21:29:56
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-24T21:29:56+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X115.0Y-85.0
X115.0Y-145.0
X165.0Y-85.0
X165.0Y-145.0
T0
M30
